const roles = [
  ['Executive Sponsor (Store Owner)',270000,'Approves budget, ensures strategic alignment, and authorizes major decisions.','people'],['Project Manager',99440,'Oversees project planning, scheduling, resource allocation, and reporting.','people'],['Retail Manager',72000,'Provides operational insight and ensures the system fits daily store processes.','people'],['IT Department / IT Specialist',80000,'Handles software installation, device setup, system integration, and technical support.','people'],['Vendor Software Representative',70000,'Provides software installation assistance, troubleshooting, and training.','people'],['Marketing Manager',102000,'Ensures inventory data integrates with product promotions and website availability when applicable.','people'],['Chief of Financial Operations (& Purchasing Officer)',120000,'Oversees budget, approves purchases, ensures ROI, and manages hardware, devices, and licensing agreements.','people'],['Security Manager (Cyber & Physical)',100000,'Verifies data protection, user access control, and device security.','people'],['Operations Manager (Training Coordinator)',60000,'Coordinates store staff scheduling for training and weekly inventory updates.','people'],['Store Staff (End Users)',45760,'Use handheld devices for inventory updates and daily stock input.','people'],
  ['Inventory Management Software',3000,'Main system for tracking stock, locations, and reorder levels.','assets'],['Handheld Devices (Scanners/Tablets)',600,'Used by staff for weekly inventory updates and item location input.','assets'],['Computers / Laptops',900,'Used by management and IT for system administration.','assets'],['Networking Equipment',1000,'Supports handheld device connectivity throughout the store.','assets'],['Training Materials',500,'Guides, manuals, and visual aids for onboarding users.','assets'],['Data Backup System or Cloud Backup Service',300,'Ensures inventory data is securely stored and recoverable.','assets']
];
const wbs = [
 ['Project Initiation',[['1.1','Define project objectives and scope','Project Manager, Executive Sponsor','—'],['1.2','Identify key stakeholders','Project Manager','SS'],['1.3','Develop project charter and obtain approval','Project Manager, Executive Sponsor','FS'],['1.4','Assign team roles and responsibilities','Project Manager, HR/Operations Manager','SF']],'Project Initiation Complete'],
 ['Project Planning',[['2.1','Develop project schedule and milestones','Project Manager','FS'],['2.2','Estimate resource requirements and costs','Project Manager, CFO','SS'],['2.3','Identify potential risks and mitigation strategies','Project Manager, Security Manager','SS'],['2.4','Conduct project kickoff meeting','Project Manager, All Department Heads','FS']],'Project Planning Complete'],
 ['Software & Hardware Procurement',[['3.1','Evaluate and select inventory management software','IT Department, Vendor Representative','SS'],['3.2','Obtain vendor proposals and finalize contracts','Project Manager, Executive Sponsor','SF'],['3.3','Purchase handheld devices and computers','IT Department, CFO','SS'],['3.4','Acquire backup storage and network upgrades','IT Department, Security Manager','SS']],'Procurement Process Complete'],
 ['System Setup & Configuration',[['4.1','Install and configure software','IT Department, Vendor Representative','FS'],['4.2','Connect handheld devices and ensure compatibility','IT Department','FS'],['4.3','Integrate system with POS','IT Department, Vendor Representative','SS'],['4.4','Establish backup storage and recovery settings','IT Department, Security Manager','SS']],'Setup & Configuration Complete'],
 ['Data Entry & Migration',[['5.1','Gather and clean existing inventory data','Operations Staff, Retail Manager','FS'],['5.2','Upload data into new system','IT Department','SS'],['5.3','Assign item locations within store','Retail Manager, Store Staff','FF'],['5.4','Verify data accuracy and sync','IT Department, Operations Manager','SS']],'Data Entry & Migration Complete'],
 ['Testing & Quality Management',[['6.1','Conduct pilot test in one department','IT Department, Retail Manager','FS'],['6.2','Identify and fix data/system errors','IT Department, Vendor Representative','SS'],['6.3','Perform full functionality testing','IT Department, Security Manager','FF'],['6.4','Obtain user acceptance sign-off','Project Manager, Executive Sponsor','FF']],'Testing & Quality Management Complete'],
 ['Training & Change Management',[['7.1','Develop training materials and manuals','HR Department, IT Department','FS'],['7.2','Train managers on system administration','IT Department','FS'],['7.3','Conduct staff training on handheld devices','IT Department, Operations Manager','FS'],['7.4','Gather feedback from training sessions','HR Department, Project Manager','FS']],'Training & Change Management Complete'],
 ['Implementation / Go-Live',[['8.1','Deploy system storewide','IT Department, Project Manager','FS'],['8.2','Assign weekly inventory update schedule','Retail Manager, Operations Manager','SS'],['8.3','Provide on-site technical support','IT Department, Vendor Representative','SS'],['8.4','Monitor system performance and feedback','Project Manager, IT Department','SS']],'Go-Live Complete; meets requirements'],
 ['Project Closure',[['9.1','Conduct post-implementation review','Project Manager, Executive Sponsor','FS'],['9.2','Document lessons learned and recommendations','Project Manager','FS'],['9.3','Release project resources','Project Manager','FF'],['9.4','Obtain final approval and close project','Executive Sponsor','FS']],'Full Project Completion']
];
const money=value=>value.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function renderCostGraph(id,type){const data=roles.filter(role=>role[3]===type).sort((a,b)=>b[1]-a[1]);const max=data[0][1];document.getElementById(id).innerHTML=`<div class="cost-bars">${data.map(role=>`<button class="cost-bar ${type}" data-index="${roles.indexOf(role)}" aria-label="${role[0]}, ${money(role[1])}" style="--width:${Math.max(role[1]/max*100,8)}%"><span class="cost-label" title="${role[0]}">${role[0]}</span><span class="cost-track"><i></i><strong>${money(role[1])}</strong></span></button>`).join('')}</div>`;document.querySelectorAll(`#${id} .cost-bar`).forEach(button=>button.addEventListener('click',()=>showRole(Number(button.dataset.index))));}
function showRole(index){const [name,cost,responsibility,type]=roles[index];document.querySelectorAll('.cost-bar').forEach(button=>button.classList.toggle('active',Number(button.dataset.index)===index));document.getElementById('roleDetail').innerHTML=`<span class="type">${type==='people'?'Role':'Asset'}</span><div><h3>${name}</h3><p>${responsibility}</p></div><strong>${money(cost)}</strong>`;}
function weekRange(index){return `Weeks ${index*4+1}–${index*4+4}`;}
function renderRoadmap(){const tabs=document.getElementById('phaseTabs');tabs.innerHTML=wbs.map((phase,index)=>`<button id="phase-tab-${index}" class="phase-tab" role="tab" aria-selected="${index===0}" aria-controls="phaseDetail" tabindex="${index===0?0:-1}" data-phase="${index}"><span class="number">${String(index+1).padStart(2,'0')}</span><strong>${phase[0]}</strong><span class="weeks">${weekRange(index)}</span><span class="milestone">◆ ${phase[2]}</span></button>`).join('');tabs.querySelectorAll('.phase-tab').forEach(button=>{button.addEventListener('click',()=>selectPhase(Number(button.dataset.phase)));button.addEventListener('keydown',event=>{if(!['ArrowRight','ArrowLeft','ArrowDown','ArrowUp'].includes(event.key))return;event.preventDefault();const current=Number(button.dataset.phase);const next=(current+(event.key==='ArrowRight'||event.key==='ArrowDown'?1:8))%9;selectPhase(next);tabs.children[next].focus();});});selectPhase(0);}
function selectPhase(index){const phase=wbs[index];document.querySelectorAll('.phase-tab').forEach((button,i)=>{button.setAttribute('aria-selected',String(i===index));button.tabIndex=i===index?0:-1;});document.getElementById('phaseDetail').setAttribute('aria-labelledby',`phase-tab-${index}`);document.getElementById('phaseDetail').innerHTML=`<div class="detail-header"><div><p class="phase-label">Selected phase ${index+1} of 9</p><h3>${phase[0]}</h3></div><span>${weekRange(index)}</span></div><div class="task-list">${phase[1].map(task=>`<div class="task-row"><b>${task[0]}</b><span>${task[1]}</span><span class="owner">${task[2]}</span><span class="dependency" title="Dependency type">${task[3]}</span></div>`).join('')}</div><p class="phase-milestone">◆ Milestone: ${phase[2]}</p>`;}
renderCostGraph('peopleCostChart','people');renderCostGraph('assetCostChart','assets');showRole(0);renderRoadmap();
